name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: [self-hosted, linux, x64]

    steps:
    - uses: actions/checkout@v4
    - name: Get Timestamp
      run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag playground:$TIMESTAMP
    - name: Run Docker Image
      run: docker run -d -p 3000:80 playground:$TIMESTAMP
